name: Vue

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    vue-tests:
        runs-on: ubuntu-latest

        steps:
            - name: "Checkout code"
              uses: actions/checkout@v3
            - name: "Use Node.js 18.17.1"
              uses: actions/setup-node@v3
              with:
                  node-version: 18.15.0
            - name: Install dependencies
              run: yarn install --frozen-lockfile
            - name: Run Build
              run: yarn dev
